spring:
  application:
    name: Produtos API
  datasource:
    url: jdbc:h2:mem:products
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console # path default to access the H2 console
  sql:
    init:
      mode: always
