-- Criação da tabela com IDENTITY (funciona melhor com H2)
CREATE TABLE PRODUCT (
                         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         NAME VARCHAR(100) NOT NULL,
                         DESCRIPTION VARCHAR(500),
                         PRICE DECIMAL(10,2) NOT NULL
);

-- Inserções sem especificar o ID
INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES
                                                   ('Smartphone X', 'Último modelo com câmera de 108MP', 3599.99),
                                                   ('Notebook Pro', '16GB RAM, SSD 512GB, tela 15.6"', 5299.00),
                                                   ('Fone Bluetooth', 'Cancelamento de ruído ativo', 899.90),
                                                   ('Smartwatch', 'Monitoramento de saúde e GPS', 1299.50),
                                                   ('Tablet 10"', '128GB armazenamento, caneta inclusa', 2199.00);
